<div class="wrap about-wrap">
	<h1>WP Faker 1.0.0</h1>
		<div class="about-text cptui-about-text">
			Thank you for choosing WP Faker! We hope that your experience with our plugin makes creating <b>fake users, fake posts & custom posts, fake woocommerce products</b> quick and easy.
			</div>
		<div class="cptui-badge"></div>

		
		<h2>What our plugin provides?</h2>
		<div class="changelog about-integrations">
			<div class="cptui-feature feature-section col three-col">
				<div class="col">
					<h2>Fake users</h2>
					<p>As the name, "fake users" sounds like something illegal but actually its not. The main purpose of generating fake users is to check the functionality which is related to multiple users.</p>
				</div>
				<div class="col">
					<h2>Fake posts & custom posts</h2>
					<p>Fake posts and custom posts again is for testing purpose only.</p>
				</div>
				<div class="col last-feature">
					<h2>Fake woocommerce products</h2>
					<p>Generating dummy/fake products is most important when you are dealing with woocommerce theme development or some functionality related to woocommerce.</p>
				</div>
			</div>
		</div>

		<div class="extranotes">
			<h1>Worried about deleting data generated by this plugin?</h1>
			<div class="wdspromos-about">
			<p>
			Don't worry about that. We provide a link in the settings section using which you can delete your fake posts, fake users, fake wocommerce products all in single click. Your actual posts, custom posts, users or products will remain as it is.
			</p>
			<p>
				<b>Enjoy the features of WP Faker!!!</b>
			</p>
			</div>		
		</div>
		<?php 
		for ($i=0; $i < 10 ; $i++) { 
			# code...
			wpfkrGeneratePosts(); 
		}
		?>
	</div>