<div class="wrap wpfkr-about-wrap about-wrap">
	<h1>WP Faker <?=WPFKR_PLUGIN_NAME_VERSION?></h1>
	<div class="wpfkr-about-text">
		Thank you for choosing WP Faker! We hope that your experience with our plugin makes creating <b>fake users, fake posts & custom posts, fake woocommerce products</b> quick and easy.
	</div>
	<h2>What our plugin provides?</h2>
	<div class="wpfkr-about-integrations">
		<div class="wpfkr-feature feature-section col three-col">
			<div class="col wpfkr-col wpfkrPanelWrapper">
				<div class="wpfkrPanelHeading">Fake wp users</div>
				<div class="wpfkrPanelBody">
					<p>As the name, "fake users" sounds like something illegal but actually its not. The main purpose of generating fake users is to check the functionality which is related to multiple users.</p>
					<p class="wpfkrLinkWrapper">
						<a href="?page=wpfkr-users">Generate users</a>
					</p>
				</div>
			</div>
			<div class="col wpfkr-col wpfkrPanelWrapper">
				<div class="wpfkrPanelHeading">Fake posts</div>
				<div class="wpfkrPanelBody">
					<p>You can generate fake wordpress default posts. This is for testing purpose only.</p>
					<p class="wpfkrLinkWrapper">
						<a href="?page=wpfkr-posts">Generate posts</a>
					</p>
				</div>
			</div>
			<div class="col wpfkr-col wpfkrPanelWrapper">
				<div class="wpfkrPanelHeading">Fake custom posts</div>
				<div class="wpfkrPanelBody">
					<p>You can generate fake wordpress custom posts. This is again for testing purpose only.</p>
					<p class="wpfkrLinkWrapper">
						<a href="?page=wpfkr-posts">Generate custom posts</a>
					</p>
				</div>
			</div>
			<div class="col wpfkr-col wpfkrPanelWrapper">
				<div class="wpfkrPanelHeading">Fake woocommerce products</div>
				<div class="wpfkrPanelBody">
					<p>Woocommerce dummy prodcuts are very important for e-commerce theme development. You can generate n number of woocommerce prodcts using this plugin.</p>
					<p class="wpfkrLinkWrapper">
						<a href="?page=wpfkr-products">Generate products</a>
					</p>
				</div>
			</div>
		</div>

	</div>

	<div class="wpfkr-extranotes">
		<h2>Worried about deleting data generated by WP Faker plugin?</h2>
		<div class="wpfkr-wdspromos-about">
			<p>
			Don't worry about that. We provide a link in each section using which you can delete your fake posts and fake users all in single click. Your actual posts, custom posts or users will remain as it is.
			</p>
			<p>
				<b>Enjoy the features of WP Faker!!!</b>
			</p>
		</div>		
	</div>
</div>