<div class="wrap wpfkr-about-wrap about-wrap">
	<h1>WP Faker 1.0.0</h1>
	<div class="wpfkr-about-text">
		Thank you for choosing WP Faker! We hope that your experience with our plugin makes creating <b>fake users, fake posts & custom posts, fake woocommerce products</b> quick and easy.
	</div>
	<h2>What our plugin provides?</h2>
	<div class="wpfkr-about-integrations">
		<div class="wpfkr-feature feature-section col three-col">
			<div class="col wpfkr-col">
				<h2>Fake wp users</h2>
				<p>As the name, "fake users" sounds like something illegal but actually its not. The main purpose of generating fake users is to check the functionality which is related to multiple users.</p>
			</div>
			<div class="col wpfkr-col">
				<h2>Fake posts</h2>
				<p>You can generate fake wordpress default posts. This is for testing purpose only.</p>
			</div>
			<div class="col wpfkr-col wpfkr-last-feature">
				<h2>Fake custom posts</h2>
				<p>You can generate fake wordpress custom posts. This is again for testing purpose only.</p>
			</div>
		</div>
	</div>

	<div class="wpfkr-extranotes">
		<h2>Worried about deleting data generated by WP Faker plugin?</h2>
		<div class="wpfkr-wdspromos-about">
			<p>
			Don't worry about that. We provide a link in each section using which you can delete your fake posts and fake users all in single click. Your actual posts, custom posts or users will remain as it is.
			</p>
			<p>
				<b>Enjoy the features of WP Faker!!!</b>
			</p>
		</div>		
	</div>
</div>