<?php
global $wpdb;
$users = get_users(array(
    'meta_key'     => 'wpfkr_user',
    'meta_value'   => 'true',
    'meta_compare' => '=',
));
if(isset($_GET['action']) && $_GET['action'] == 'wpfkr_deleteusers'){
	foreach ($users as $key => $userDatavalue){
		wp_delete_user($userDatavalue->ID);
	}
	wp_redirect("admin.php?page=Users&tab=view_users&status=success");
}
$actual_link = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
 ?>
 <h2>Bellow are all the users generated by this plugin 
 	<?php if ( !empty($users) ) { ?>
	 	<span class="deleteSpan">
	 		<a onclick="return confirm('Are you sure you want to delete all fake users?')" class="wpfkr-btn wpfkr-btnRed" href="<?=$actual_link?>&action=wpfkr_deleteusers">Delete all users</a>
	 	</span>
 	<?php } ?>
 </h2>
<table id="wpfkrListPostsTbl" class="stripe" style="width:100%">
	<thead>
		<tr>
			<th>#</th>
			<th>Display name</th>
			<th>Email</th>
			<th>Role</th>
		</tr>
	</thead>
	<tbody>
		<?php
		if ( !empty($users) ) {
			$counter = 1;
			foreach ($users as $key => $userDatavalue){ ?>
				<tr>
					<td><?=$counter?></td>
					<td><?=$userDatavalue->data->display_name?></td>
					<td><?=$userDatavalue->data->user_email?></td>
					<td><?=$userDatavalue->roles[0]?></td>
				</tr>
				<?php
				$counter++;
			}
		} ?>
	</tbody>
</table>